import { HistoricalDeployment, FMEADocument } from '../types';
import { calculateRPN } from '../data/criteriaData';

const HISTORY_STORAGE_KEY = 'fmea_deployed_history_v1';

export const INITIAL_SEEDED_HISTORY: HistoricalDeployment[] = [
  {
    id: 'deploy-wm-inv10',
    title: 'Máy giặt Cửa trước Inverter 10.5kg (Dự án WM-INV10-PRO)',
    productName: 'Máy giặt Cửa trước Inverter 10.5kg',
    productCode: 'WM-INV10-PRO',
    category: 'dien_gia_dung',
    fmeaType: 'DFMEA',
    phase: 'PV (Process Verification)',
    supplier: 'R&D Thiết bị Gia dụng & Ban Dự án Động cơ',
    itemCount: 6,
    highRiskCount: 2,
    savedAt: '2026-08-28 16:45',
    note: 'Đã hoàn tất đánh giá DFMEA cho đợt thử nghiệm lắp ráp lô đầu tiên.',
    documentSnapshot: {
      id: 'doc-wm-inv10',
      fmeaType: 'DFMEA',
      productName: 'Máy giặt Cửa trước Inverter 10.5kg',
      productCode: 'WM-INV10-PRO',
      category: 'dien_gia_dung',
      phase: 'PV (Process Verification)',
      supplier: 'R&D Thiết bị Gia dụng & Ban Dự án Động cơ',
      location: 'Nhà máy Sản xuất Máy giặt & Thiết bị Điện tử',
      assemblyTest: 'Đạt yêu cầu đồng tâm trục lồng giặt và giảm chấn lò xo',
      functionalTest: 'Vắt 1400 vòng/phút, độ ồn dưới 68dB, cân bằng tải trọng lệch tâm',
      periodicTest: 'Chạy thử nghiệm giặt 3000 chu trình tiêu chuẩn IEC 60456',
      author: 'Nguyễn Văn Toàn',
      reviewer: 'Trần Đức Minh',
      approver: 'Phạm Hoàng Nam',
      createdDate: '2026-08-10',
      updatedDate: '2026-08-28',
      items: [
        {
          id: 'wm-1',
          itemNo: 1,
          componentName: 'Cụm Động cơ BLDC Dẫn động trực tiếp',
          riskIssue: 'Độ ồn & Rung động',
          failureMode: 'Rung lắc mạnh và tiếng kêu rít khi vắt tốc độ cao 1400 rpm',
          cause: 'Bạc đạn (vòng bi) trục bị rơ lắc hoặc dung sai gia công gá motor vượt ngưỡng',
          currentControl: 'Kiểm tra rung động bằng gia tốc kế tại trạm test cuối chuyền',
          S: 8,
          O: 3,
          D: 4,
          rpn: 96,
          conclusion: 'Cần cải tiến',
          action: 'Chuyển đổi sang vòng bi NSK tiêu chuẩn C3 và siết chặt dung sai ép trục H7/js6',
          pic: 'Trần Văn Mạnh (R&D)',
          startDate: '2026-08-12',
          dueDate: '2026-08-26',
          status: 'completed',
          result: 'Độ rung giảm 42%, tiếng ồn đo được ở 1400rpm chỉ 64dB đạt chuẩn',
          sAfter: 8,
          oAfter: 1,
          dAfter: 2,
          rpnAfter: 16,
        },
        {
          id: 'wm-2',
          itemNo: 2,
          componentName: 'Bo mạch công suất Inverter (IPM)',
          riskIssue: 'An toàn điện & Tản nhiệt',
          failureMode: 'Cháy nổ linh kiện IGBT khi giặt quá tải hoặc điện áp nguồn dao động',
          cause: 'Nhiệt độ module IGBT vượt ngưỡng 125°C do keo tản nhiệt không phủ đều',
          currentControl: 'Cảm biến nhiệt NTC gắn trên tản nhiệt nhôm ngắt bảo vệ ở 95°C',
          S: 9,
          O: 2,
          D: 3,
          rpn: 54,
          conclusion: 'Cần cải tiến',
          action: 'Áp dụng máy tra keo tản nhiệt tự động định lượng và mở rộng cánh tản nhiệt nhôm đúc 15%',
          pic: 'Lê Hoàng Sơn (Phần cứng)',
          startDate: '2026-08-14',
          dueDate: '2026-08-27',
          status: 'completed',
          result: 'Nhiệt độ đỉnh tải nặng giảm xuống 78°C, an toàn tuyệt đối',
          sAfter: 9,
          oAfter: 1,
          dAfter: 2,
          rpnAfter: 18,
        },
        {
          id: 'wm-3',
          itemNo: 3,
          componentName: 'Bơm xả nước và Bộ lọc bẫy cặn',
          riskIssue: 'Chức năng xả',
          failureMode: 'Nước trong lồng không xả được, máy báo lỗi OE/E03',
          cause: 'Cánh bơm xả bị kẹt do dị vật (tiền xu, kẹp tóc, xơ vải vón cục)',
          currentControl: 'Lưới lọc cặn cơ khí có thể tháo rời ở mặt trước máy',
          S: 6,
          O: 4,
          D: 2,
          rpn: 48,
          conclusion: 'Cần cải tiến',
          action: 'Thiết kế lại buồng bẫy xoáy ly tâm và bổ sung thuật toán tự đảo chiều cánh bơm 3 lần khi kẹt',
          pic: 'Đỗ Quang Dũng',
          startDate: '2026-08-15',
          dueDate: '2026-08-28',
          status: 'in_progress',
          result: 'Đã hoàn thiện mẫu in 3D buồng bẫy cặn mới',
          sAfter: 6,
          oAfter: 2,
          dAfter: 2,
          rpnAfter: 24,
        },
        {
          id: 'wm-4',
          itemNo: 4,
          componentName: 'Gioăng cao su cửa trước (Door Gasket)',
          riskIssue: 'Kín nước & Vệ sinh',
          failureMode: 'Rò rỉ nước ra sàn nhà hoặc đọng nước gây nấm mốc đen',
          cause: 'Lỗ thoát nước đáy gioăng bị bít tắc hoặc mép gioăng ép không đều',
          currentControl: 'Thử nghiệm phun nước áp lực cao vào khe cửa 3 bar',
          S: 7,
          O: 3,
          D: 2,
          rpn: 42,
          conclusion: 'Cần cải tiến',
          action: 'Mở rộng 3 lỗ thoát nước đáy gioăng từ phi 4mm lên phi 7mm và bổ sung phụ gia kháng khuẩn Ag+',
          pic: 'Vũ Thị Hằng (Vật liệu)',
          startDate: '2026-08-16',
          dueDate: '2026-08-30',
          status: 'completed',
          result: 'Nước thoát hết 100% sau chu trình giặt',
          sAfter: 7,
          oAfter: 1,
          dAfter: 2,
          rpnAfter: 14,
        },
        {
          id: 'wm-5',
          itemNo: 5,
          componentName: 'Van cấp nước đôi Solenoid',
          riskIssue: 'Cấp nước & Rò rỉ',
          failureMode: 'Cấp nước liên tục không ngắt dù đã tắt máy (tràn nước)',
          cause: 'Màng cao su van điện từ bị kẹt cặn cát hoặc lò xo hồi vị gãy mỏi',
          currentControl: 'Test đóng mở 100.000 chu kỳ với nước chứa tạp chất nhẹ',
          S: 8,
          O: 2,
          D: 2,
          rpn: 32,
          conclusion: 'Không cải tiến',
          action: 'Duy trì lưới lọc inox 100 mesh tại đầu cấp nước vào và kiểm tra lực đàn hồi lò xo SUS304',
          pic: 'Nguyễn Văn Toàn',
          startDate: '2026-08-10',
          dueDate: '2026-08-20',
          status: 'completed',
          result: 'Đạt độ bền 120.000 lần đóng ngắt',
        },
        {
          id: 'wm-6',
          itemNo: 6,
          componentName: 'Cảm biến rung 3D MEMS & Cân bằng tải',
          riskIssue: 'An toàn vận hành',
          failureMode: 'Máy không phát hiện được đồ giặt bị dồn một phía, gây va đập thùng máy',
          cause: 'Độ nhạy cảm biến con quay hồi chuyển bị trôi nhiệt độ hoặc thuật toán lọc nhiễu chậm',
          currentControl: 'Kiểm tra mô phỏng tải lệch 1.2kg trong buồng thử rung',
          S: 8,
          O: 2,
          D: 3,
          rpn: 48,
          conclusion: 'Cần cải tiến',
          action: 'Cập nhật thuật toán Kalman filter nhận diện tải lệch chỉ sau 2 vòng quay đảo chiều',
          pic: 'Ngô Minh Tuấn (Thuật toán)',
          startDate: '2026-08-18',
          dueDate: '2026-08-31',
          status: 'completed',
          result: 'Thời gian nhận diện tải lệch rút ngắn từ 45 giây xuống 12 giây',
          sAfter: 8,
          oAfter: 1,
          dAfter: 1,
          rpnAfter: 8,
        },
      ],
    },
  },
  {
    id: 'deploy-rs-g30l',
    title: 'Bình nước nóng Rossi Grand 30L (Dự án RS-G30L)',
    productName: 'Bình nước nóng Rossi Grand 30L',
    productCode: 'RS-G30L',
    category: 'bon_nuoc',
    fmeaType: 'DFMEA',
    phase: 'MP (Mass Production)',
    supplier: 'Phòng Thiết kế Cơ Nhiệt & Nhà máy Rossi',
    itemCount: 5,
    highRiskCount: 2,
    savedAt: '2026-08-22 10:15',
    note: 'Hồ sơ tiêu chuẩn chống rò điện và chống nổ áp lực nước bình Rossi 30L.',
    documentSnapshot: {
      id: 'doc-rs-g30l',
      fmeaType: 'DFMEA',
      productName: 'Bình nước nóng Rossi Grand 30L',
      productCode: 'RS-G30L',
      category: 'bon_nuoc',
      phase: 'MP (Mass Production)',
      supplier: 'Phòng Thiết kế Cơ Nhiệt & Nhà máy Rossi',
      location: 'Khu công nghiệp Tân Á Đại Thành',
      assemblyTest: 'Thử áp lực thủy lực ruột bình 15 bar trong 5 phút không rò rỉ',
      functionalTest: 'Đun sôi 30L nước từ 20°C lên 75°C trong 25 phút, công suất 2500W',
      periodicTest: 'Thử nghiệm shock nhiệt 1000 chu kỳ và chống giật ELCB 15mA/0.05s',
      author: 'Trần Văn Kiên',
      reviewer: 'Lê Văn Hiển',
      approver: 'Nguyễn Tiến Dũng',
      createdDate: '2026-08-01',
      updatedDate: '2026-08-22',
      items: [
        {
          id: 'rs-1',
          itemNo: 1,
          componentName: 'Cọc đốt đun nước Incoloy 840',
          riskIssue: 'An toàn điện giật',
          failureMode: 'Cọc đốt bị nứt vỏ bọc dẫn đến rò điện 220V ra dòng nước tắm',
          cause: 'Bị ăn mòn điện hóa do nước cứng nhiễm canxi/magie hoặc quá nhiệt cục bộ đóng cặn',
          currentControl: 'Cầu dao chống rò điện ELCB lưỡng cực ngắt ở ngưỡng 15mA trong 0.03s',
          S: 10,
          O: 2,
          D: 2,
          rpn: 40,
          conclusion: 'Cần cải tiến',
          action: 'Nâng cấp thanh nhiệt sang Incoloy 840 siêu bền bỉ mạ men Sapphire và tích hợp thanh Magie kích thước lớn',
          pic: 'Trần Văn Kiên',
          startDate: '2026-08-05',
          dueDate: '2026-08-18',
          status: 'completed',
          result: 'Tuổi thọ cọc đốt tăng gấp đôi trong điều kiện nước cứng 350ppm CaCO3',
          sAfter: 10,
          oAfter: 1,
          dAfter: 1,
          rpnAfter: 10,
        },
        {
          id: 'rs-2',
          itemNo: 2,
          componentName: 'Rơ le nhiệt lưỡng kim kép (Thermostat + Thermal Cutout)',
          riskIssue: 'Chống nổ áp suất',
          failureMode: 'Tiếp điểm rơ le bị dính tiếp điểm không ngắt, bình đun sôi liên tục tăng áp suất',
          cause: 'Phóng tia lửa điện hồ quang làm dính chảy tiếp điểm bạc sau nhiều năm hoạt động',
          currentControl: 'Rơ le an toàn cấp 2 tự nhảy cưỡng bức ngắt cả 2 cực pha và mass ở 93°C',
          S: 9,
          O: 2,
          D: 2,
          rpn: 36,
          conclusion: 'Không cải tiến',
          action: 'Duy trì sử dụng rơ le nhiệt kép Cotherm nhập khẩu Pháp đạt chứng chỉ CE/TUV',
          pic: 'Lê Văn Hiển',
          startDate: '2026-08-08',
          dueDate: '2026-08-20',
          status: 'completed',
          result: 'Đạt kiểm định ngắt an toàn 50.000 chu kỳ thử nghiệm',
        },
        {
          id: 'rs-3',
          itemNo: 3,
          componentName: 'Ruột bình thép tráng men kim cương nhân tạo',
          riskIssue: 'Độ bền cơ & Kín nước',
          failureMode: 'Bục đường hàn ruột bình gây rò rỉ nước làm hỏng trần thạch cao',
          cause: 'Khuyết tật mối hàn hồ quang chìm hoặc độ bám dính men thủy tinh không đồng đều tại mép bo',
          currentControl: 'Kiểm tra áp lực thủy lực 1.6 MPa (16 bar) 100% sản phẩm trên chuyền',
          S: 7,
          O: 2,
          D: 2,
          rpn: 28,
          conclusion: 'Không cải tiến',
          action: 'Ứng dụng công nghệ hàn laser tự động đa trục và tráng men ướt tĩnh điện nung 860°C',
          pic: 'Nguyễn Văn Hoàng',
          startDate: '2026-08-02',
          dueDate: '2026-08-15',
          status: 'completed',
          result: 'Tỷ lệ rò rỉ tại xưởng hàn giảm xuống dưới 0.05%',
        },
        {
          id: 'rs-4',
          itemNo: 4,
          componentName: 'Van an toàn xả áp 1 chiều (Safety Relief Valve)',
          riskIssue: 'Xả áp an toàn',
          failureMode: 'Van bị kẹt cặn bẩn không xả áp khi áp lực bình vượt quá 8.5 bar',
          cause: 'Lò xo nén inox bị đóng cặn canxi hoặc cặn cát đọng cứng buồng van',
          currentControl: 'Gạt tay xả cặn định kỳ có cần gạt cưỡng bức bên hông van',
          S: 9,
          O: 2,
          D: 3,
          rpn: 54,
          conclusion: 'Cần cải tiến',
          action: 'Thiết kế van an toàn tích hợp lưới lọc cặn thô và gioăng silicon tự làm sạch',
          pic: 'Trần Văn Kiên',
          startDate: '2026-08-10',
          dueDate: '2026-08-22',
          status: 'completed',
          result: 'Đảm bảo tự động xả áp chính xác ở 8.0 ± 0.3 bar',
          sAfter: 9,
          oAfter: 1,
          dAfter: 1,
          rpnAfter: 9,
        },
        {
          id: 'rs-5',
          itemNo: 5,
          componentName: 'Thanh Magie (Magnesium Anode)',
          riskIssue: 'Chống ăn mòn ruột bình',
          failureMode: 'Thanh Magie tan quá nhanh trong vòng 6 tháng làm mất tác dụng bảo vệ ruột bình',
          cause: 'Hàm lượng magie nguyên chất thấp hoặc nước có nồng độ clorua và sunfat cao',
          currentControl: 'Kiểm tra thành phần quang phổ vật liệu Magie đầu vào đạt >99%',
          S: 7,
          O: 3,
          D: 3,
          rpn: 63,
          conclusion: 'Cần cải tiến',
          action: 'Tăng đường kính thanh Magie từ phi 18mm lên phi 22mm x dài 250mm cho dòng bình cao cấp',
          pic: 'Lê Văn Hiển',
          startDate: '2026-08-12',
          dueDate: '2026-08-25',
          status: 'completed',
          result: 'Kéo dài thời gian bảo vệ ruột bình lên trên 24 tháng liên tục',
          sAfter: 7,
          oAfter: 1,
          dAfter: 2,
          rpnAfter: 14,
        },
      ],
    },
  },
  {
    id: 'deploy-sakura-ic88',
    title: 'Bếp từ đôi Inverter Sakura (Quy trình PFMEA Lắp ráp)',
    productName: 'Bếp từ đôi Inverter Sakura',
    productCode: 'IC-8800PLUS',
    category: 'thiet_bi_nha_bep',
    fmeaType: 'PFMEA',
    phase: 'PV (Process Verification)',
    supplier: 'Xưởng Lắp ráp Thiết bị Nhà Bếp & QA',
    itemCount: 5,
    highRiskCount: 1,
    savedAt: '2026-08-15 14:20',
    note: 'Quy trình kiểm soát công đoạn lắp ráp mâm từ, bo mạch công suất và kiểm tra cao áp.',
    documentSnapshot: {
      id: 'doc-sakura-ic88',
      fmeaType: 'PFMEA',
      productName: 'Bếp từ đôi Inverter Sakura',
      productCode: 'IC-8800PLUS',
      category: 'thiet_bi_nha_bep',
      phase: 'PV (Process Verification)',
      supplier: 'Xưởng Lắp ráp Thiết bị Nhà Bếp & QA',
      location: 'Nhà máy Lắp ráp Thiết bị Bếp Sakura',
      assemblyTest: 'Dung sai phẳng mặt kính Kanger dưới 0.5mm, lực nén mâm từ 15N',
      functionalTest: 'Đun 1L nước sôi trong 2 phút 15 giây chế độ Booster 2400W, nhận diện đáy nồi',
      periodicTest: 'Kiểm tra phóng điện áp cao Hi-Pot 3750V/2mA/1s và thử nghiệm sốc nhiệt kính',
      author: 'Hoàng Văn Lâm',
      reviewer: 'Đặng Quốc Huy',
      approver: 'Nguyễn Văn Thắng',
      createdDate: '2026-07-25',
      updatedDate: '2026-08-15',
      items: [
        {
          id: 'pf-1',
          itemNo: 1,
          componentName: 'Công đoạn 01: Dán mặt kính gốm Ceramic vào khung đỡ',
          riskIssue: 'Kín nước bề mặt',
          failureMode: 'Nước canh sôi tràn trên mặt bếp rò rỉ xuống khoang bo mạch phía dưới',
          cause: 'Bắn keo silicon RTV không liên tục, bị đứt nét hoặc chiều cao gờ keo dưới 1.5mm',
          currentControl: 'Kiểm tra trực quan bằng mắt thường và soi gương góc nghiêng',
          S: 8,
          O: 4,
          D: 5,
          rpn: 160,
          conclusion: 'Cần cải tiến',
          action: 'Đầu tư robot bắn keo tự động 3 trục điều áp liên tục và dưỡng định vị khung chuẩn',
          pic: 'Hoàng Văn Lâm (PE)',
          startDate: '2026-07-28',
          dueDate: '2026-08-10',
          status: 'completed',
          result: 'Đường keo đều 100%, vượt qua bài test ngâm nước mặt kính chuẩn IPX4',
          sAfter: 8,
          oAfter: 1,
          dAfter: 1,
          rpnAfter: 8,
        },
        {
          id: 'pf-2',
          itemNo: 2,
          componentName: 'Công đoạn 02: Lắp ráp cụm mâm đồng cảm ứng từ (Coil)',
          riskIssue: 'Hiệu suất đun nấu',
          failureMode: 'Mâm từ bị kênh nghiêng, khoảng cách tới đáy nồi không đều gây nóng lệch',
          cause: 'Lò xo đàn hồi đỡ mâm từ bị kẹt gá hoặc siết ốc cố định lệch lực',
          currentControl: 'Dùng thước đo khe hở lá thép kiểm tra tại 4 góc mâm từ',
          S: 6,
          O: 3,
          D: 3,
          rpn: 54,
          conclusion: 'Cần cải tiến',
          action: 'Trang bị tô vít điện tự dừng có kiểm soát mô-men siết lực chuẩn 1.2 Nm cho 4 ốc gá',
          pic: 'Đặng Quốc Huy (QC)',
          startDate: '2026-08-01',
          dueDate: '2026-08-12',
          status: 'completed',
          result: 'Khoảng cách mâm từ tới kính đạt chuẩn 3.0 ± 0.2mm trên 100% sản phẩm',
          sAfter: 6,
          oAfter: 1,
          dAfter: 2,
          rpnAfter: 12,
        },
        {
          id: 'pf-3',
          itemNo: 3,
          componentName: 'Công đoạn 03: Bắt vít bán dẫn IGBT vào tấm tản nhiệt nhôm',
          riskIssue: 'Giải nhiệt công suất',
          failureMode: 'Nổ linh kiện IGBT sau 10-15 phút nấu do quá nhiệt tiếp xúc',
          cause: 'Công nhân quên bôi mỡ tản nhiệt hoặc siết ốc chưa đủ chặt làm hở khe không khí',
          currentControl: 'Đo nhiệt độ bề mặt IGBT bằng súng hồng ngoại ngẫu nhiên 3 mẫu/ca',
          S: 9,
          O: 3,
          D: 4,
          rpn: 108,
          conclusion: 'Cần cải tiến',
          action: 'Chuyển sang dùng miếng đệm tản nhiệt silicon định hình dán sẵn Poka-Yoke chống quên',
          pic: 'Hoàng Văn Lâm',
          startDate: '2026-08-02',
          dueDate: '2026-08-14',
          status: 'completed',
          result: 'Loại bỏ hoàn toàn lỗi quên tra mỡ tản nhiệt, nhiệt độ IGBT ổn định 65°C',
          sAfter: 9,
          oAfter: 1,
          dAfter: 1,
          rpnAfter: 9,
        },
        {
          id: 'pf-4',
          itemNo: 4,
          componentName: 'Công đoạn 04: Thử nghiệm điện áp cao an toàn (Hi-Pot Test)',
          riskIssue: 'An toàn tính mạng',
          failureMode: 'Sản phẩm bị rò điện áp cao ra vỏ kim loại nhưng máy test không báo lỗi',
          cause: 'Điểm tiếp xúc que kẹp mass máy test bị bẩn oxy hóa hoặc dây nối mass đứt ngầm',
          currentControl: 'Hiệu chuẩn máy Hi-Pot định kỳ hàng tuần',
          S: 10,
          O: 2,
          D: 3,
          rpn: 60,
          conclusion: 'Cần cải tiến',
          action: 'Áp dụng bài test mẫu chuẩn (Golden Sample) trước mỗi ca sản xuất để xác nhận máy test ngắt tốt',
          pic: 'Nguyễn Văn Thắng',
          startDate: '2026-08-05',
          dueDate: '2026-08-15',
          status: 'completed',
          result: 'Đảm bảo máy test phát hiện dòng rò >2mA ngắt tức thì trong 0.1s',
          sAfter: 10,
          oAfter: 1,
          dAfter: 1,
          rpnAfter: 10,
        },
        {
          id: 'pf-5',
          itemNo: 5,
          componentName: 'Công đoạn 05: Kiểm tra chức năng đun nước Booster & Độ ồn quạt',
          riskIssue: 'Chất lượng trải nghiệm',
          failureMode: 'Bếp không kích hoạt được công suất cực đại Booster 2400W hoặc quạt ồn >55dB',
          cause: 'Dây tín hiệu giao tiếp bo hiển thị cắm lỏng chân hoặc cánh quạt chạm dây điện',
          currentControl: 'Trạm chạy thử tự động đo công suất tiêu thụ và micro đo decibel',
          S: 6,
          O: 3,
          D: 2,
          rpn: 36,
          conclusion: 'Không cải tiến',
          action: 'Duy trì trạm test tự động 100% có gá kẹp dây cố định bằng đai thít chuyên dụng',
          pic: 'Đặng Quốc Huy',
          startDate: '2026-08-05',
          dueDate: '2026-08-15',
          status: 'completed',
          result: '100% đạt công suất 2400W ± 3% và độ ồn dưới 50dB',
        },
      ],
    },
  },
];

/**
 * Lấy danh sách lịch sử đã triển khai từ Local Storage (kèm dữ liệu mẫu ban đầu)
 */
export function getHistoryList(): HistoricalDeployment[] {
  try {
    const raw = localStorage.getItem(HISTORY_STORAGE_KEY);
    if (!raw) {
      // Khởi tạo dữ liệu mẫu ban đầu vào storage
      localStorage.setItem(HISTORY_STORAGE_KEY, JSON.stringify(INITIAL_SEEDED_HISTORY));
      return INITIAL_SEEDED_HISTORY;
    }
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed) && parsed.length > 0) {
      return parsed;
    }
    return INITIAL_SEEDED_HISTORY;
  } catch (err) {
    console.error('Lỗi khi đọc lịch sử triển khai:', err);
    return INITIAL_SEEDED_HISTORY;
  }
}

/**
 * Lưu hồ sơ FMEA hiện tại vào danh sách lịch sử
 */
export function saveCurrentDocumentToHistory(
  document: FMEADocument,
  customTitle?: string,
  note?: string
): HistoricalDeployment {
  const currentList = getHistoryList();
  
  const now = new Date();
  const dateStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')} ${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;
  
  const highRiskCount = document.items.filter(i => (i.rpn >= 100 || i.S >= 8)).length;

  const newDeployment: HistoricalDeployment = {
    id: `deploy-${Date.now()}-${Math.random().toString(36).substring(2, 6)}`,
    title: customTitle?.trim() || `${document.productName} (${document.productCode || 'Hồ sơ'} • ${document.fmeaType})`,
    productName: document.productName,
    productCode: document.productCode,
    category: document.category,
    fmeaType: document.fmeaType,
    phase: document.phase,
    supplier: document.supplier,
    itemCount: document.items.length,
    highRiskCount,
    savedAt: dateStr,
    note: note?.trim() || `Lưu từ bảng làm việc (${document.items.length} mục phân tích, ${highRiskCount} cảnh báo)`,
    documentSnapshot: JSON.parse(JSON.stringify(document)),
  };

  const updatedList = [newDeployment, ...currentList];
  try {
    localStorage.setItem(HISTORY_STORAGE_KEY, JSON.stringify(updatedList));
    window.dispatchEvent(new Event('fmea_history_changed'));
  } catch (err) {
    console.error('Lỗi khi lưu lịch sử:', err);
  }

  return newDeployment;
}

/**
 * Xóa một bản ghi lịch sử
 */
export function deleteHistoryItem(id: string): HistoricalDeployment[] {
  const currentList = getHistoryList();
  const filtered = currentList.filter(item => item.id !== id);
  try {
    localStorage.setItem(HISTORY_STORAGE_KEY, JSON.stringify(filtered));
    window.dispatchEvent(new Event('fmea_history_changed'));
  } catch (err) {
    console.error('Lỗi khi xóa lịch sử:', err);
  }
  return filtered;
}

/**
 * Khôi phục lại danh sách mẫu mặc định ban đầu
 */
export function resetHistoryToDefault(): HistoricalDeployment[] {
  try {
    localStorage.setItem(HISTORY_STORAGE_KEY, JSON.stringify(INITIAL_SEEDED_HISTORY));
    window.dispatchEvent(new Event('fmea_history_changed'));
  } catch (err) {
    console.error('Lỗi khi đặt lại lịch sử:', err);
  }
  return INITIAL_SEEDED_HISTORY;
}
